[workspace]
authors = ["obi <ole.bialas@posteo.de>"]
channels = ["conda-forge"]
name = "new_website"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
seaborn = ">=0.13.2,<0.14"
pyarrow = ">=21.0.0,<22"
ipykernel = ">=6.30.1,<7"

[pypi-dependencies]
jupyter = ">=1.1.1, <2"
mne = ">=1.10.1, <2"
meegkit = ">=0.1.9, <0.2"
pyprep = ">=0.5.0, <0.6"
autoreject = ">=0.4.3, <0.5"
unitmatchpy = ">=2.41, <3"
spikeinterface = ">=0.103.0, <0.104"
numba = ">=0.62.1, <0.63"
ttkthemes = ">=3.2.2, <4"
